"""
City name to IATA airport code lookup.
Covers the most common travel destinations worldwide.
"""

CITY_TO_IATA: dict[str, str] = {
    # North America
    "new york": "JFK",
    "new york city": "JFK",
    "nyc": "JFK",
    "los angeles": "LAX",
    "la": "LAX",
    "chicago": "ORD",
    "houston": "IAH",
    "miami": "MIA",
    "san francisco": "SFO",
    "seattle": "SEA",
    "boston": "BOS",
    "washington": "IAD",
    "washington dc": "IAD",
    "atlanta": "ATL",
    "dallas": "DFW",
    "denver": "DEN",
    "las vegas": "LAS",
    "orlando": "MCO",
    "phoenix": "PHX",
    "toronto": "YYZ",
    "montreal": "YUL",
    "vancouver": "YVR",
    "mexico city": "MEX",
    "cancun": "CUN",

    # Europe
    "london": "LHR",
    "paris": "CDG",
    "amsterdam": "AMS",
    "frankfurt": "FRA",
    "madrid": "MAD",
    "barcelona": "BCN",
    "rome": "FCO",
    "milan": "MXP",
    "venice": "VCE",
    "florence": "FLR",
    "naples": "NAP",
    "zurich": "ZRH",
    "vienna": "VIE",
    "brussels": "BRU",
    "lisbon": "LIS",
    "porto": "OPO",
    "athens": "ATH",
    "istanbul": "IST",
    "moscow": "SVO",
    "st. petersburg": "LED",
    "saint petersburg": "LED",
    "stockholm": "ARN",
    "oslo": "OSL",
    "copenhagen": "CPH",
    "helsinki": "HEL",
    "dublin": "DUB",
    "edinburgh": "EDI",
    "munich": "MUC",
    "berlin": "BER",
    "hamburg": "HAM",
    "prague": "PRG",
    "budapest": "BUD",
    "warsaw": "WAW",
    "bucharest": "OTP",
    "sofia": "SOF",
    "zagreb": "ZAG",
    "dubrovnik": "DBV",
    "split": "SPU",
    "reykjavik": "KEF",

    # Asia
    "tokyo": "NRT",
    "osaka": "KIX",
    "kyoto": "ITM",
    "seoul": "ICN",
    "beijing": "PEK",
    "shanghai": "PVG",
    "hong kong": "HKG",
    "taipei": "TPE",
    "singapore": "SIN",
    "bangkok": "BKK",
    "phuket": "HKT",
    "chiang mai": "CNX",
    "bali": "DPS",
    "jakarta": "CGK",
    "kuala lumpur": "KUL",
    "manila": "MNL",
    "ho chi minh city": "SGN",
    "saigon": "SGN",
    "hanoi": "HAN",
    "mumbai": "BOM",
    "delhi": "DEL",
    "new delhi": "DEL",
    "bangalore": "BLR",
    "chennai": "MAA",
    "kolkata": "CCU",
    "dubai": "DXB",
    "abu dhabi": "AUH",
    "doha": "DOH",
    "riyadh": "RUH",
    "tel aviv": "TLV",
    "amman": "AMM",
    "karachi": "KHI",
    "colombo": "CMB",
    "kathmandu": "KTM",
    "dhaka": "DAC",

    # Africa
    "cairo": "CAI",
    "nairobi": "NBO",
    "johannesburg": "JNB",
    "cape town": "CPT",
    "lagos": "LOS",
    "accra": "ACC",
    "casablanca": "CMN",
    "marrakech": "RAK",
    "tunis": "TUN",
    "addis ababa": "ADD",
    "dar es salaam": "DAR",
    "kampala": "EBB",

    # Oceania
    "sydney": "SYD",
    "melbourne": "MEL",
    "brisbane": "BNE",
    "perth": "PER",
    "auckland": "AKL",
    "christchurch": "CHC",

    # South America
    "sao paulo": "GRU",
    "rio de janeiro": "GIG",
    "buenos aires": "EZE",
    "lima": "LIM",
    "bogota": "BOG",
    "santiago": "SCL",
    "caracas": "CCS",
    "quito": "UIO",
    "la paz": "LPB",
}


def city_to_iata(city: str) -> str:
    """
    Convert a city name to its primary IATA airport code.
    Returns the input unchanged if no match found
    (SerpApi also accepts city names as fallback).
    """
    return CITY_TO_IATA.get(city.strip().lower(), city)
